import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

const Poopin= Poppins({
  subsets:['latin'],
  weight: ['400', '600'],
  display: 'swap'
});
export const metadata: Metadata = {
  title: "Vision the Visualizer", 
  description: "Generated by The Endurance",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`hover:cursor-default bg-black select-none text-white ${Poopin.className} `}>
          {children}
      </body>
    </html>
  );
}
